---
- name: Execute Deployment and Service playbooks
  hosts: eks-bootstrap
  become: true

  tasks:
    - name: Download deployment.yml file to host (eks-bootstrap)
      ansible.builtin.get_url:
        url: "https://raw.github.com/Devnikops/gitops-register-app/main/deployment.yaml"
        dest: "/home/ubuntu/workspace/"
        mode: '0744'

    - name: Download service.yml file to host (eks-bootstrap)
      ansible.builtin.get_url:
        url: "https://raw.github.com/Devnikops/gitops-register-app/main/service.yaml"
        dest: "/home/ubuntu/workspace/"
        mode: '0744'
    
    - name: Build the Tomcat container
      command: docker build -t nikhil999999/register-app-pipeline:latest https://github.com/Devnikops/gitops-register-app/tree/main

    - name: Run the Tomcat container
      command: docker run -d --name tom_container -p 8080:8080 tomcat:latest

    - name: Create container from the docker image
      command: docker run -d --name app_container -p 8081:8080 nikhil999999/register-app-pipeline:latest
